# Generated by Django 3.2.18 on 2023-12-07 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('evalue_nom', models.CharField(max_length=200)),
                ('evalue_prenom', models.CharField(max_length=200)),
                ('evalue_poste', models.CharField(max_length=200)),
                ('evaluateur_nom', models.CharField(max_length=200)),
                ('evaluateur_prenom', models.CharField(max_length=200)),
                ('evaluateur_poste', models.CharField(max_length=200)),
                ('commentaire', models.TextField()),
                ('owner_evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalue_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Repondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repondant1_nom', models.CharField(max_length=200)),
                ('repondant1_prenom', models.CharField(max_length=200)),
                ('repondant1_mail', models.EmailField(max_length=200)),
                ('repondant2_nom', models.CharField(max_length=200)),
                ('repondant2_prenom', models.CharField(max_length=200)),
                ('repondant2_mail', models.EmailField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repondant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repondants', to='evaluationapp.evaluation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evaluations', to='evaluationapp.thematique'),
        ),
    ]
